-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 19, 2021 at 08:42 PM
-- Server version: 10.1.36-MariaDB
-- PHP Version: 7.2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `stockbit_test`
--

-- --------------------------------------------------------

--
-- Table structure for table `api_logs`
--

CREATE TABLE `api_logs` (
  `id_api_log` int(11) NOT NULL,
  `response` text,
  `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `api_logs`
--

INSERT INTO `api_logs` (`id_api_log`, `response`, `created_date`) VALUES
(1, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-19 23:45:05\",\"executionTime\":\"1ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/refactor/get?str=apa(xyz)coba(satu)dua(tiga(empat)lima)\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"param\":\"apa(xyz)coba(satu)dua(tiga(empat)lima)\",\"oldFunc\":\"xyz\",\"newFunc\":\"xyz\"}}}}', '2021-10-19 16:52:25'),
(2, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:10:16\",\"executionTime\":\"2ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/refactor/get?str=apa(xyz)coba(satu)dua(tiga(empat)lima)\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"param\":\"apa(xyz)coba(satu)dua(tiga(empat)lima)\",\"oldFunc\":\"xyz\",\"newFunc\":\"xyz\"}}}}', '2021-10-19 17:10:17'),
(3, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:13:02\",\"executionTime\":\"1ms\",\"request\":{\"method\":\"POST\",\"url\":\"/api/anagram/check-anagram\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[[\"kita\",\"atik\",\"tika\"],[\"aku\",\"kua\"],[\"kia\"],[\"makan\"]]}}}', '2021-10-19 17:13:02'),
(4, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:13:45\",\"executionTime\":\"1ms\",\"request\":{\"method\":\"POST\",\"url\":\"/api/anagram/check-anagram\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[[\"kita\",\"atik\",\"tika\"],[\"aku\",\"kua\"],[\"kia\"],[\"makan\"]]}}}', '2021-10-19 17:13:45'),
(5, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:15:13\",\"executionTime\":\"1ms\",\"request\":{\"method\":\"POST\",\"url\":\"/api/anagram/check-anagram\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[[\"kita\",\"atik\",\"tika\"],[\"aku\",\"kua\"],[\"kia\"],[\"makan\"]]}}}', '2021-10-19 17:15:14'),
(6, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:15:27\",\"executionTime\":\"1ms\",\"request\":{\"method\":\"POST\",\"url\":\"/api/anagram/check-anagram\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[[\"kita\",\"atik\",\"tika\"],[\"aku\",\"kua\"],[\"kia\"],[\"makan\"]]}}}', '2021-10-19 17:15:27'),
(7, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:21:33\",\"executionTime\":\"543ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/search?title=batman\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"Search\":[{\"Title\":\"Batman Begins\",\"Year\":\"2005\",\"imdbID\":\"tt0372784\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Batman v Superman: Dawn of Justice\",\"Year\":\"2016\",\"imdbID\":\"tt2975590\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Batman\",\"Year\":\"1989\",\"imdbID\":\"tt0096895\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg\"},{\"Title\":\"Batman Returns\",\"Year\":\"1992\",\"imdbID\":\"tt0103776\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_SX300.jpg\"},{\"Title\":\"Batman Forever\",\"Year\":\"1995\",\"imdbID\":\"tt0112462\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg\"},{\"Title\":\"Batman & Robin\",\"Year\":\"1997\",\"imdbID\":\"tt0118688\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_SX300.jpg\"},{\"Title\":\"The Lego Batman Movie\",\"Year\":\"2017\",\"imdbID\":\"tt4116284\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_SX300.jpg\"},{\"Title\":\"Batman: The Animated Series\",\"Year\":\"1992–1995\",\"imdbID\":\"tt0103359\",\"Type\":\"series\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTM3MTRkZjQtYjBkMy00YWE1LTkxOTQtNDQyNGY0YjYzNzAzXkEyXkFqcGdeQXVyOTgwMzk1MTA@._V1_SX300.jpg\"},{\"Title\":\"Batman: Under the Red Hood\",\"Year\":\"2010\",\"imdbID\":\"tt1569923\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNmY4ZDZjY2UtOWFiYy00MjhjLThmMjctOTQ2NjYxZGRjYmNlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg\"},{\"Title\":\"Batman: The Dark Knight Returns, Part 1\",\"Year\":\"2012\",\"imdbID\":\"tt2313197\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMzIxMDkxNDM2M15BMl5BanBnXkFtZTcwMDA5ODY1OQ@@._V1_SX300.jpg\"}],\"totalResults\":\"466\",\"Response\":\"True\"}}}}', '2021-10-19 17:21:34'),
(8, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:22:34\",\"executionTime\":\"102ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/search?Title=batman\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"Search\":[{\"Title\":\"Batman Begins\",\"Year\":\"2005\",\"imdbID\":\"tt0372784\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Batman v Superman: Dawn of Justice\",\"Year\":\"2016\",\"imdbID\":\"tt2975590\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Batman\",\"Year\":\"1989\",\"imdbID\":\"tt0096895\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg\"},{\"Title\":\"Batman Returns\",\"Year\":\"1992\",\"imdbID\":\"tt0103776\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_SX300.jpg\"},{\"Title\":\"Batman Forever\",\"Year\":\"1995\",\"imdbID\":\"tt0112462\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg\"},{\"Title\":\"Batman & Robin\",\"Year\":\"1997\",\"imdbID\":\"tt0118688\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_SX300.jpg\"},{\"Title\":\"The Lego Batman Movie\",\"Year\":\"2017\",\"imdbID\":\"tt4116284\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_SX300.jpg\"},{\"Title\":\"Batman: The Animated Series\",\"Year\":\"1992–1995\",\"imdbID\":\"tt0103359\",\"Type\":\"series\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTM3MTRkZjQtYjBkMy00YWE1LTkxOTQtNDQyNGY0YjYzNzAzXkEyXkFqcGdeQXVyOTgwMzk1MTA@._V1_SX300.jpg\"},{\"Title\":\"Batman: Under the Red Hood\",\"Year\":\"2010\",\"imdbID\":\"tt1569923\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNmY4ZDZjY2UtOWFiYy00MjhjLThmMjctOTQ2NjYxZGRjYmNlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg\"},{\"Title\":\"Batman: The Dark Knight Returns, Part 1\",\"Year\":\"2012\",\"imdbID\":\"tt2313197\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMzIxMDkxNDM2M15BMl5BanBnXkFtZTcwMDA5ODY1OQ@@._V1_SX300.jpg\"}],\"totalResults\":\"466\",\"Response\":\"True\"}}}}', '2021-10-19 17:22:34'),
(9, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:22:53\",\"executionTime\":\"481ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/search?imdbID=tt0372784\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"Search\":[{\"Title\":\"Undefined\",\"Year\":\"2006\",\"imdbID\":\"tt1436480\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTgzNzkxMzk5Nl5BMl5BanBnXkFtZTgwMTQ2MzA2MDE@._V1_SX300.jpg\"},{\"Title\":\"The Undefined\",\"Year\":\"2013\",\"imdbID\":\"tt3271334\",\"Type\":\"movie\",\"Poster\":\"N/A\"},{\"Title\":\"A Love Undefined\",\"Year\":\"2016\",\"imdbID\":\"tt4955578\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMDNmNDUwZGEtYmMxZS00NzU5LWEyMGMtOTRhNjBkNWNjNjMwXkEyXkFqcGdeQXVyNzA5MzMzNjk@._V1_SX300.jpg\"},{\"Title\":\"Artist Undefined\",\"Year\":\"2015\",\"imdbID\":\"tt5190590\",\"Type\":\"movie\",\"Poster\":\"N/A\"},{\"Title\":\"Undefined\",\"Year\":\"2014\",\"imdbID\":\"tt5581814\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BYTk1OTcwYTQtMmEyNS00OWFiLTlmOWYtZGQ1ZDczNjc3MWFkXkEyXkFqcGdeQXVyMTAwMjMyOTE@._V1_SX300.jpg\"},{\"Title\":\"Undefined: A Muslim-American Musical\",\"Year\":\"2017\",\"imdbID\":\"tt7178924\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BODMwYTE1ZGMtMDk5Zi00ZTExLTk3MjUtMDk1NTk5Njk0ZmZhXkEyXkFqcGdeQXVyNzI4NTUyNjE@._V1_SX300.jpg\"},{\"Title\":\"Beautiful UnDefined\",\"Year\":\"2017\",\"imdbID\":\"tt7639764\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOWIwNDMzZDQtYTg1OC00ODBjLTkxZWItMzgzMzZiNjIzZGI0XkEyXkFqcGdeQXVyODIwODk5Njc@._V1_SX300.jpg\"},{\"Title\":\"Life Undefined\",\"Year\":\"2020\",\"imdbID\":\"tt10229024\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMWZmMzY5MjctMWVmMS00OTljLTgxYjgtZDhlNjYwNWJhNzRjXkEyXkFqcGdeQXVyNjExMDY4NTE@._V1_SX300.jpg\"},{\"Title\":\"Girl Undefined\",\"Year\":\"2019\",\"imdbID\":\"tt11758836\",\"Type\":\"movie\",\"Poster\":\"N/A\"},{\"Title\":\"Darro: Undefined\",\"Year\":\"2020\",\"imdbID\":\"tt13362386\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BYjQ4NDJmOWYtNDI2YS00NWM0LWE0NjktODg1NjFmNTNhZTg1XkEyXkFqcGdeQXVyMTA2MjcwOTI0._V1_SX300.jpg\"}],\"totalResults\":\"10\",\"Response\":\"True\"}}}}', '2021-10-19 17:22:54'),
(10, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:24:09\",\"executionTime\":\"490ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/detail?imdbID=tt0372784\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"Title\":\"Batman Begins\",\"Year\":\"2005\",\"Rated\":\"PG-13\",\"Released\":\"15 Jun 2005\",\"Runtime\":\"140 min\",\"Genre\":\"Action, Adventure\",\"Director\":\"Christopher Nolan\",\"Writer\":\"Bob Kane, David S. Goyer, Christopher Nolan\",\"Actors\":\"Christian Bale, Michael Caine, Ken Watanabe\",\"Plot\":\"After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.\",\"Language\":\"English, Mandarin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 1 Oscar. 13 wins & 79 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"8.2/10\"},{\"Source\":\"Rotten Tomatoes\",\"Value\":\"84%\"},{\"Source\":\"Metacritic\",\"Value\":\"70/100\"}],\"Metascore\":\"70\",\"imdbRating\":\"8.2\",\"imdbVotes\":\"1,362,365\",\"imdbID\":\"tt0372784\",\"Type\":\"movie\",\"DVD\":\"18 Oct 2005\",\"BoxOffice\":\"$206,852,432\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}}}}', '2021-10-19 17:24:10'),
(11, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:25:25\",\"executionTime\":\"3ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/users/get\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[{\"id\":1,\"userName\":\"Ali\",\"ParentUserName\":\"Budi\"},{\"id\":2,\"userName\":\"Budi\",\"ParentUserName\":null},{\"id\":3,\"userName\":\"Cecep\",\"ParentUserName\":\"Ali\"}]}}}', '2021-10-19 17:25:25'),
(12, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:46:56\",\"executionTime\":\"0ms\",\"request\":{\"method\":\"GET\",\"url\":\"/todos\",\"body\":{}},\"response\":{\"statusCode\":404,\"body\":{\"status\":false,\"message\":\"Error\"}}}', '2021-10-19 17:46:56'),
(13, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:46:56\",\"executionTime\":\"1ms\",\"request\":{\"method\":\"GET\",\"url\":\"/todos/1\",\"body\":{}},\"response\":{\"statusCode\":404,\"body\":{\"status\":false,\"message\":\"Error\"}}}', '2021-10-19 17:46:56'),
(14, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:46:56\",\"executionTime\":\"0ms\",\"request\":{\"method\":\"GET\",\"url\":\"/todos/10\",\"body\":{}},\"response\":{\"statusCode\":404,\"body\":{\"status\":false,\"message\":\"Error\"}}}', '2021-10-19 17:46:56'),
(15, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 00:48:00\",\"executionTime\":\"1ms\",\"request\":{\"method\":\"GET\",\"url\":\"/users/get\",\"body\":{}},\"response\":{\"statusCode\":404,\"body\":{\"status\":false,\"message\":\"Error\"}}}', '2021-10-19 17:48:00'),
(16, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:33:37\",\"executionTime\":\"55ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/users/get\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[{\"id\":1,\"userName\":\"Ali\",\"ParentUserName\":\"Budi\"},{\"id\":2,\"userName\":\"Budi\",\"ParentUserName\":null},{\"id\":3,\"userName\":\"Cecep\",\"ParentUserName\":\"Ali\"}]}}}', '2021-10-19 18:33:37'),
(17, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:33:37\",\"executionTime\":\"83ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/search?Title=batman\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"Search\":[{\"Title\":\"Batman Begins\",\"Year\":\"2005\",\"imdbID\":\"tt0372784\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Batman v Superman: Dawn of Justice\",\"Year\":\"2016\",\"imdbID\":\"tt2975590\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Batman\",\"Year\":\"1989\",\"imdbID\":\"tt0096895\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg\"},{\"Title\":\"Batman Returns\",\"Year\":\"1992\",\"imdbID\":\"tt0103776\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_SX300.jpg\"},{\"Title\":\"Batman Forever\",\"Year\":\"1995\",\"imdbID\":\"tt0112462\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg\"},{\"Title\":\"Batman & Robin\",\"Year\":\"1997\",\"imdbID\":\"tt0118688\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_SX300.jpg\"},{\"Title\":\"The Lego Batman Movie\",\"Year\":\"2017\",\"imdbID\":\"tt4116284\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_SX300.jpg\"},{\"Title\":\"Batman: The Animated Series\",\"Year\":\"1992–1995\",\"imdbID\":\"tt0103359\",\"Type\":\"series\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTM3MTRkZjQtYjBkMy00YWE1LTkxOTQtNDQyNGY0YjYzNzAzXkEyXkFqcGdeQXVyOTgwMzk1MTA@._V1_SX300.jpg\"},{\"Title\":\"Batman: Under the Red Hood\",\"Year\":\"2010\",\"imdbID\":\"tt1569923\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNmY4ZDZjY2UtOWFiYy00MjhjLThmMjctOTQ2NjYxZGRjYmNlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg\"},{\"Title\":\"Batman: The Dark Knight Returns, Part 1\",\"Year\":\"2012\",\"imdbID\":\"tt2313197\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMzIxMDkxNDM2M15BMl5BanBnXkFtZTcwMDA5ODY1OQ@@._V1_SX300.jpg\"}],\"totalResults\":\"466\",\"Response\":\"True\"}}}}', '2021-10-19 18:33:37'),
(18, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:33:37\",\"executionTime\":\"78ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/search?Title=batman1232323\",\"body\":{}},\"response\":{\"statusCode\":404,\"body\":{\"status\":true,\"message\":\"Data Not Found\"}}}', '2021-10-19 18:33:37'),
(19, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:33:37\",\"executionTime\":\"76ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/detail?imdbID=tt0372784\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"Title\":\"Batman Begins\",\"Year\":\"2005\",\"Rated\":\"PG-13\",\"Released\":\"15 Jun 2005\",\"Runtime\":\"140 min\",\"Genre\":\"Action, Adventure\",\"Director\":\"Christopher Nolan\",\"Writer\":\"Bob Kane, David S. Goyer, Christopher Nolan\",\"Actors\":\"Christian Bale, Michael Caine, Ken Watanabe\",\"Plot\":\"After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.\",\"Language\":\"English, Mandarin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 1 Oscar. 13 wins & 79 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"8.2/10\"},{\"Source\":\"Rotten Tomatoes\",\"Value\":\"84%\"},{\"Source\":\"Metacritic\",\"Value\":\"70/100\"}],\"Metascore\":\"70\",\"imdbRating\":\"8.2\",\"imdbVotes\":\"1,362,365\",\"imdbID\":\"tt0372784\",\"Type\":\"movie\",\"DVD\":\"18 Oct 2005\",\"BoxOffice\":\"$206,852,432\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}}}}', '2021-10-19 18:33:37'),
(20, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:33:37\",\"executionTime\":\"77ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/detail?imdbID=tt03727841\",\"body\":{}},\"response\":{\"statusCode\":404,\"body\":{\"status\":true,\"message\":\"Data Not Found\"}}}', '2021-10-19 18:33:37'),
(21, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:33:37\",\"executionTime\":\"0ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/refactor/get?str=apa(xyz)coba(satu)dua(tiga(empat)lima)\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"param\":\"apa(xyz)coba(satu)dua(tiga(empat)lima)\",\"oldFunc\":\"xyz\",\"newFunc\":\"xyz\"}}}}', '2021-10-19 18:33:37'),
(22, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:33:37\",\"executionTime\":\"0ms\",\"request\":{\"method\":\"POST\",\"url\":\"/api/anagram/check-anagram\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[[\"kita\",\"atik\",\"tika\"],[\"aku\",\"kua\"],[\"kia\"],[\"makan\"]]}}}', '2021-10-19 18:33:37'),
(23, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:34:05\",\"executionTime\":\"55ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/users/get\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[{\"id\":1,\"userName\":\"Ali\",\"ParentUserName\":\"Budi\"},{\"id\":2,\"userName\":\"Budi\",\"ParentUserName\":null},{\"id\":3,\"userName\":\"Cecep\",\"ParentUserName\":\"Ali\"}]}}}', '2021-10-19 18:34:05'),
(24, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:34:07\",\"executionTime\":\"91ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/search?Title=batman\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"Search\":[{\"Title\":\"Batman Begins\",\"Year\":\"2005\",\"imdbID\":\"tt0372784\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Batman v Superman: Dawn of Justice\",\"Year\":\"2016\",\"imdbID\":\"tt2975590\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Batman\",\"Year\":\"1989\",\"imdbID\":\"tt0096895\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg\"},{\"Title\":\"Batman Returns\",\"Year\":\"1992\",\"imdbID\":\"tt0103776\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_SX300.jpg\"},{\"Title\":\"Batman Forever\",\"Year\":\"1995\",\"imdbID\":\"tt0112462\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg\"},{\"Title\":\"Batman & Robin\",\"Year\":\"1997\",\"imdbID\":\"tt0118688\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_SX300.jpg\"},{\"Title\":\"The Lego Batman Movie\",\"Year\":\"2017\",\"imdbID\":\"tt4116284\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_SX300.jpg\"},{\"Title\":\"Batman: The Animated Series\",\"Year\":\"1992–1995\",\"imdbID\":\"tt0103359\",\"Type\":\"series\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTM3MTRkZjQtYjBkMy00YWE1LTkxOTQtNDQyNGY0YjYzNzAzXkEyXkFqcGdeQXVyOTgwMzk1MTA@._V1_SX300.jpg\"},{\"Title\":\"Batman: Under the Red Hood\",\"Year\":\"2010\",\"imdbID\":\"tt1569923\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNmY4ZDZjY2UtOWFiYy00MjhjLThmMjctOTQ2NjYxZGRjYmNlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg\"},{\"Title\":\"Batman: The Dark Knight Returns, Part 1\",\"Year\":\"2012\",\"imdbID\":\"tt2313197\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMzIxMDkxNDM2M15BMl5BanBnXkFtZTcwMDA5ODY1OQ@@._V1_SX300.jpg\"}],\"totalResults\":\"466\",\"Response\":\"True\"}}}}', '2021-10-19 18:34:07'),
(25, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:34:09\",\"executionTime\":\"480ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/search?Title=batman1232323\",\"body\":{}},\"response\":{\"statusCode\":404,\"body\":{\"status\":true,\"message\":\"Data Not Found\"}}}', '2021-10-19 18:34:09'),
(26, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:34:11\",\"executionTime\":\"75ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/detail?imdbID=tt0372784\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"Title\":\"Batman Begins\",\"Year\":\"2005\",\"Rated\":\"PG-13\",\"Released\":\"15 Jun 2005\",\"Runtime\":\"140 min\",\"Genre\":\"Action, Adventure\",\"Director\":\"Christopher Nolan\",\"Writer\":\"Bob Kane, David S. Goyer, Christopher Nolan\",\"Actors\":\"Christian Bale, Michael Caine, Ken Watanabe\",\"Plot\":\"After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.\",\"Language\":\"English, Mandarin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 1 Oscar. 13 wins & 79 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"8.2/10\"},{\"Source\":\"Rotten Tomatoes\",\"Value\":\"84%\"},{\"Source\":\"Metacritic\",\"Value\":\"70/100\"}],\"Metascore\":\"70\",\"imdbRating\":\"8.2\",\"imdbVotes\":\"1,362,365\",\"imdbID\":\"tt0372784\",\"Type\":\"movie\",\"DVD\":\"18 Oct 2005\",\"BoxOffice\":\"$206,852,432\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}}}}', '2021-10-19 18:34:11'),
(27, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:34:13\",\"executionTime\":\"87ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/detail?imdbID=tt03727841\",\"body\":{}},\"response\":{\"statusCode\":404,\"body\":{\"status\":true,\"message\":\"Data Not Found\"}}}', '2021-10-19 18:34:13'),
(28, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:34:15\",\"executionTime\":\"0ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/refactor/get?str=apa(xyz)coba(satu)dua(tiga(empat)lima)\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"param\":\"apa(xyz)coba(satu)dua(tiga(empat)lima)\",\"oldFunc\":\"xyz\",\"newFunc\":\"xyz\"}}}}', '2021-10-19 18:34:15'),
(29, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:34:17\",\"executionTime\":\"0ms\",\"request\":{\"method\":\"POST\",\"url\":\"/api/anagram/check-anagram\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[[\"kita\",\"atik\",\"tika\"],[\"aku\",\"kua\"],[\"kia\"],[\"makan\"]]}}}', '2021-10-19 18:34:17'),
(30, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:36:09\",\"executionTime\":\"55ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/users/get\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[{\"id\":1,\"userName\":\"Ali\",\"ParentUserName\":\"Budi\"},{\"id\":2,\"userName\":\"Budi\",\"ParentUserName\":null},{\"id\":3,\"userName\":\"Cecep\",\"ParentUserName\":\"Ali\"}]}}}', '2021-10-19 18:36:09'),
(31, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:36:09\",\"executionTime\":\"126ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/search?Title=batman\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"Search\":[{\"Title\":\"Batman Begins\",\"Year\":\"2005\",\"imdbID\":\"tt0372784\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Batman v Superman: Dawn of Justice\",\"Year\":\"2016\",\"imdbID\":\"tt2975590\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Batman\",\"Year\":\"1989\",\"imdbID\":\"tt0096895\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg\"},{\"Title\":\"Batman Returns\",\"Year\":\"1992\",\"imdbID\":\"tt0103776\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_SX300.jpg\"},{\"Title\":\"Batman Forever\",\"Year\":\"1995\",\"imdbID\":\"tt0112462\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg\"},{\"Title\":\"Batman & Robin\",\"Year\":\"1997\",\"imdbID\":\"tt0118688\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_SX300.jpg\"},{\"Title\":\"The Lego Batman Movie\",\"Year\":\"2017\",\"imdbID\":\"tt4116284\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_SX300.jpg\"},{\"Title\":\"Batman: The Animated Series\",\"Year\":\"1992–1995\",\"imdbID\":\"tt0103359\",\"Type\":\"series\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTM3MTRkZjQtYjBkMy00YWE1LTkxOTQtNDQyNGY0YjYzNzAzXkEyXkFqcGdeQXVyOTgwMzk1MTA@._V1_SX300.jpg\"},{\"Title\":\"Batman: Under the Red Hood\",\"Year\":\"2010\",\"imdbID\":\"tt1569923\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNmY4ZDZjY2UtOWFiYy00MjhjLThmMjctOTQ2NjYxZGRjYmNlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg\"},{\"Title\":\"Batman: The Dark Knight Returns, Part 1\",\"Year\":\"2012\",\"imdbID\":\"tt2313197\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMzIxMDkxNDM2M15BMl5BanBnXkFtZTcwMDA5ODY1OQ@@._V1_SX300.jpg\"}],\"totalResults\":\"466\",\"Response\":\"True\"}}}}', '2021-10-19 18:36:09'),
(32, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:36:09\",\"executionTime\":\"79ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/search?Title=batman1232323\",\"body\":{}},\"response\":{\"statusCode\":404,\"body\":{\"status\":true,\"message\":\"Data Not Found\"}}}', '2021-10-19 18:36:09'),
(33, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:36:09\",\"executionTime\":\"101ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/detail?imdbID=tt0372784\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"Title\":\"Batman Begins\",\"Year\":\"2005\",\"Rated\":\"PG-13\",\"Released\":\"15 Jun 2005\",\"Runtime\":\"140 min\",\"Genre\":\"Action, Adventure\",\"Director\":\"Christopher Nolan\",\"Writer\":\"Bob Kane, David S. Goyer, Christopher Nolan\",\"Actors\":\"Christian Bale, Michael Caine, Ken Watanabe\",\"Plot\":\"After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.\",\"Language\":\"English, Mandarin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 1 Oscar. 13 wins & 79 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"8.2/10\"},{\"Source\":\"Rotten Tomatoes\",\"Value\":\"84%\"},{\"Source\":\"Metacritic\",\"Value\":\"70/100\"}],\"Metascore\":\"70\",\"imdbRating\":\"8.2\",\"imdbVotes\":\"1,362,365\",\"imdbID\":\"tt0372784\",\"Type\":\"movie\",\"DVD\":\"18 Oct 2005\",\"BoxOffice\":\"$206,852,432\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}}}}', '2021-10-19 18:36:09'),
(34, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:36:09\",\"executionTime\":\"82ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/omdb/detail?imdbID=tt03727841\",\"body\":{}},\"response\":{\"statusCode\":404,\"body\":{\"status\":true,\"message\":\"Data Not Found\"}}}', '2021-10-19 18:36:09'),
(35, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:36:09\",\"executionTime\":\"0ms\",\"request\":{\"method\":\"GET\",\"url\":\"/api/refactor/get?str=apa(xyz)coba(satu)dua(tiga(empat)lima)\",\"body\":{}},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":{\"param\":\"apa(xyz)coba(satu)dua(tiga(empat)lima)\",\"oldFunc\":\"xyz\",\"newFunc\":\"xyz\"}}}}', '2021-10-19 18:36:09'),
(36, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:36:09\",\"executionTime\":\"1ms\",\"request\":{\"method\":\"POST\",\"url\":\"/api/anagram/check-anagram\",\"body\":[\"kita\",\"atik\",\"tika\",\"aku\",\"kia\",\"makan\",\"kua\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[[\"kita\",\"atik\",\"tika\"],[\"aku\",\"kua\"],[\"kia\"],[\"makan\"]]}}}', '2021-10-19 18:36:09'),
(37, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:36:18\",\"executionTime\":\"1ms\",\"request\":{\"method\":\"POST\",\"url\":\"/api/anagram/check-anagram\",\"body\":[\"aca\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[[\"aca\"]]}}}', '2021-10-19 18:36:18'),
(38, '{\"appName\":\"STOCKBIT-TEST\",\"requestTime\":\"2021-10-20 01:36:41\",\"executionTime\":\"1ms\",\"request\":{\"method\":\"POST\",\"url\":\"/api/anagram/check-anagram\",\"body\":[\"aca\"]},\"response\":{\"statusCode\":200,\"body\":{\"status\":true,\"message\":\"Success\",\"data\":[[\"aca\"]]}}}', '2021-10-19 18:36:41');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `parent` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `parent`) VALUES
(1, 'Ali', 2),
(2, 'Budi', 0),
(3, 'Cecep', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `api_logs`
--
ALTER TABLE `api_logs`
  ADD PRIMARY KEY (`id_api_log`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `api_logs`
--
ALTER TABLE `api_logs`
  MODIFY `id_api_log` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
